server:
  port: 9000
spring:
  application:
    name: msa-board-article-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/msaboard
    username: msaboard
    password: 1234
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none