server:
  port: 9001
spring:
  application:
    name: msa-board-comment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/comment
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none